python:
  - https://realpython.com/

testing:
  - https://www.softwaretestinghelp.com/
  - https://www.smartsheet.com/test-case-templates-examples
  - https://www.tacticalprojectmanager.com/
  - https://strongqa.com/
tips:
  - https://devhints.io/
  - https://shellmagic.xyz/
  - https://www.runoob.com/

shell:
  - https://devhints.io/bash

tools:
  - https://buildkite.com/
  - https://www.ranorex.com/
  - https://blog.gurock.com/
  - https://smartbear.com/
  - https://help.github.com/en/github/getting-started-with-github/faq-about-changes-to-githubs-plans?utm_source=announcement&utm_medium=email&utm_campaig
  - https://logz.io
  
admin:
  - https://github.com/YuKongEr/panda-cloud.git
    