#name: update awesome-stars
#on:
#  schedule:
#  - cron: 30 0 * * *
#jobs:
#  awesome-stars:
#    name: update stars
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v1
#    - name: Set up Python
#      uses: actions/setup-python@v1
#      with:
#        python-version: 3.8
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt
#    - name: update repo
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      run: python collector_commander.py gh_stars  && cp -rf starred_repo.json data/github/starred && pytest tests/test_readme_render.py && cp tests/README.md .