github:
  - https://github.com/maxdome/swagger-combine
  - https://github.com/WindomZ/swagger-merger
  - https://github.com/schroedermatt/swagger-aggregate
  - https://github.com/notaryio/notary
  - https://github.com/paulvollmer/openapi-split
  - https://github.com/wikimedia/swagger-router
  - https://github.com/a2dict/swagger-apis
  - https://github.com/algoo/hapic
  - https://github.com/agriya/tixmall